### ISSUE TITLE
Fails to update mhc package from 3.3.3 to 3.3.4

### ISSUE THREAD

**Issue by JPortici** [Microchip-MPLAB-Harmony/contentmanager#1]
MPLABX (5.30) prompted me to update the harmony 3 configurato plugin, so i did.
Then, i opened the content manager standalone and it still indicated v3.3.3 for the mhc repo, so i clicked update. Once udpated i closed MPLABX
After a couple of seconds the prompt: "mhc" package update failed!

Then i opened MPLABX again and went for the content manager. The content manager still showed "mhc" at v3.3.3 with the update to 3.3.4 available. It also showed CMSIS-FreeRTOS (which didn't appear when launched standalone)
Click update, still fails after a couple of seconds. Internet connection probably not to blame but i'll retry later

Log Trace, INFO
![immagine](https://user-images.githubusercontent.com/8018188/69622680-c018f080-1041-11ea-9b98-a6599c7055e0.png)

Log Trace, DEBUG is the same.

Ah, i had to take a picture because i can't copy the text on the log view?

EDIT: Happens the same on another machine, on another location, on another connection

**Comment by aethaniel** [comment]
It's possible your existing set of repositories was wrongly updating using previous tool Framework Downloader. 
Do you mind downloading the Harmony 3 modules you need to a new location, please?

**Comment by JPortici** [comment]
You mean, launch the content manager in the **current** folder, change the framework folder and download again, to see if it works? or just re-download?

**Comment by aethaniel** [comment]
Well, you describe 2 different use case: MPlab X plugin. In this case, use it to download from scratch in another framework root location from inside MPlab X.
Else clone yourself this repository from scratch somewhere and do the same as previous use case and download everything to a new framework root location.
