### ISSUE TITLE
MCC unusable since core v1.3.0

### ISSUE THREAD

**Issue by DanieleNardi** [Microchip-MPLAB-Harmony/contentmanager#13]
Hello,
I tried to follow this tutorial https://microchipdeveloper.com/harmony3:new-proj-with-mcc, but MCC stops during loading due to a incompatibility with core harmony v3 v1.3.0.
The output from MPLAB X is the following:

> 10:02:05.974    INFO: Fetching list of available libraries.
> 10:02:07.043    INFO: Download Complete: C:\Users\NardiD\.mcc\mcc_libraries.xml
> 10:02:08.969    INFO: Start MCC
> 10:02:08.994    INFO: Core v5.4.11 loaded.
> 10:04:25.850 WARNING: Unable to load project: 
> Incompatible with core: Harmony V3 v1.3.0
> 
> All library versions are available for download in the MCC Content Manager, or on the MCC website. www.microchip.com/mcc
> 10:07:00.242    INFO: Stop MCC
> 10:07:00.282    INFO: Core v5.4.11 unloaded.

Attached you can find the log from mcc.

Older project with core 1.2.0 can be opened, but update to core 1.3.0 results in the same identical issue.

Other infos:
OS: Windows 10
MPLAB X IDE v6.0
MPLAB Code Configurator Plugin 5.1.17
MPLAB HAmrony 3 Launcher Plugin 3.6.4

Best regards,
Daniele
[mcc_error_log.txt](https://github.com/Microchip-MPLAB-Harmony/contentmanager/files/11076754/mcc_error_log.txt)

**Comment by fhriley** [comment]
I am running into this issue, also. I am attempting to run [this demo app](https://github.com/Microchip-MPLAB-Harmony/csp_apps_sam_d21_da1/tree/master/apps/tc/tc_capture_mode), but I cannot open it since upgrading content manager to v2.3.7. I was on v2.1.something before and it could open and upgrade this project. Is it possible to downgrade content manager so I can use this project again?

**Comment by DanieleNardi** [comment]
> I am running into this issue, also. I am attempting to run [this demo app](https://github.com/Microchip-MPLAB-Harmony/csp_apps_sam_d21_da1/tree/master/apps/tc/tc_capture_mode), but I cannot open it since upgrading content manager to v2.3.7. I was on v2.1.something before and it could open and upgrade this project. Is it possible to downgrade content manager so I can use this project again?
> 
> <img alt="error" width="272" src="https://user-images.githubusercontent.com/153649/229690060-4d23cdb7-99a1-4815-bf48-f22c4fa843e7.png">

I received the following solutions from Microchip Support Team:
1) Upgrade MPLAB X IDE to version 6.05 so that you can use new version of MCC plugin which is compatible with Harmony Core 1.3.0
2) Delete Harmony core 1.3.0 from menù Tools -> Options -> Plugin Tab -> MPLAC Code Configurator Tab -> Remove Library, in the new window select Software -> Harmony V3 -> Harmony V3 (1.3.0)

**Comment by baldhead69** [comment]
Where i download the "MCC harmony core" v1.2.0  ???

In "mcc content manager wizard" only v1.3.1 appears for download and that version dont work for me.

**Comment by DanieleNardi** [comment]
> Where i can download the "MCC harmony core" v1.2.0 ???
> 
> In "mcc content manager wizard" only v1.3.1 appears for download and that version dont work for me.

Which version of MPLABXIDE and MCC plugin are you using?

**Comment by baldhead69** [comment]
I managed to solve it, I installed mplab x v6.05 from scratch and deleted all related folders in c:\users\user\.....

Upate all pluggins in tool pluggins.

I also changed my project's *.mc3 file.  mcc v5.5.0 and harmony v1.2.0 and now it worked.

only the local littlefs on my computer, which mcc itself downloaded, is not being recognized.
