### ISSUE TITLE
Content Manager 1.3.1 takes 5 minutes to load catalog information

### ISSUE THREAD

**Issue by RikusW** [Microchip-MPLAB-Harmony/contentmanager#5]
There is a lot of hard disk activity, mostly seeks from the sound of it seems only to read a few MB per second.

**Comment by aethaniel** [comment]
@RikusW, sorry for late answer here, my bad.
Do you still have the issue? I think it has been solved with CM v1.4.0.

**Comment by RikusW** [comment]
@aethaniel I haven't used it in quite a while since the project I was working on is done, will check later.

**Comment by RikusW** [comment]
@aethaniel You probably have an SSD, there are 7 java processes open seen in iotop, so multiple files being accessed and seek time degrade performance significantly, still taking  a very long time to open even on v1.5.0 with hard disk thrashing all the way and basically making the whole system unusable.
Multithreaded io access is not good for an old HDD...
