### ISSUE TITLE
Visual C++ Runtime error during package download

### ISSUE THREAD

**Issue by vassdaniel** [Microchip-MPLAB-Harmony/contentmanager#6]
Hi All,

I get this error message when I try to download the packages in Content manager. I try to install 3 packages and I get this error message 3 times, then I get a message from content manager that download failed.

![image](https://user-images.githubusercontent.com/26670496/78876671-f9ca2100-7a4f-11ea-82fd-a0b61e9cd057.png)

**Comment by aethaniel** [comment]
This issue has been solved by more recent releases
