### ISSUE TITLE
Content manager throwing : Error in getting remote packages 

### ISSUE THREAD

**Issue by arun-kmr** [Microchip-MPLAB-Harmony/contentmanager#7]
Hi All, I am getting following errors, when content manager is trying to load the catalog. Nothing is being load and the error in images below in being received.
![image](https://user-images.githubusercontent.com/29814622/87298284-90165300-c527-11ea-9e68-743a80233e39.png)
![image](https://user-images.githubusercontent.com/29814622/87298397-c18f1e80-c527-11ea-9382-86a937c17e6f.png)

**Comment by arun-kmr** [comment]
Please find the complete log below.
[content-manager-log.txt](https://github.com/Microchip-MPLAB-Harmony/contentmanager/files/4913358/content-manager-log.txt)

**Comment by aethaniel** [comment]
solved by more recent release
