### ISSUE TITLE
Standalone Contentmanager do not use system proxy

### ISSUE THREAD

**Issue by pustekuchen91** [Microchip-MPLAB-Harmony/contentmanager#8]
When starting the Harmony Content Manger from command line with runme.bat no connection is possible, when sitting behind a proxy.

At default the system proxy should be used

Possible solutions doesnt work: 
`java -jar harmony-content-manager.jar -Djava.net.useSystemProxies=true`
`
java -jar harmony-content-manager.jar -Dhttp.proxyHost=10.10.10.10 -Dhttp.proxyPort=8080 -Dhttp.proxyUser=username -Dhttp.proxyPassword=password `

**Comment by pustekuchen91** [comment]
@MPLABHarmony @aethaniel is someone caring about issues here or would it better to contact the microchip support?

**Comment by aethaniel** [comment]
@pustekuchen91, we are the development team. Sorry for being late on this.
I know you found a solution by configuring the system network settings for proxy.
