### ISSUE TITLE
Cant download packages behind proxy

### ISSUE THREAD

**Issue by pustekuchen91** [Microchip-MPLAB-Harmony/contentmanager#9]
I cant download packages via the conent manager on a fresh installed PC. I think the problem are the proxy settings. The content manager can succesfully connect. But when i start downloading some packages i get the following errors:

![grafik](https://user-images.githubusercontent.com/7147324/101895633-12bf3f00-3ba8-11eb-946f-406ef95020cf.png)

in Harmony3/csp is just a .git folder while the above message is shown. after closing the error the folder dissappears

Debug Log 
![grafik](https://user-images.githubusercontent.com/7147324/101895959-895c3c80-3ba8-11eb-85bb-22ccc7f526f5.png)

![grafik](https://user-images.githubusercontent.com/7147324/101896492-61210d80-3ba9-11eb-924a-3b6d66dfc06f.png)

Proxy is configured in MPLAB X. maybe the proxy settings are not forwared to the git calls?

as a workaround I've manually cloned all needed repos. Please provide a fix

**Comment by aethaniel** [comment]
Hi, sorry for late answer. 
CM is independant from MPLAB X. It is using system settings regarding proxy, etc...
Furthermore, it is using only HTTPS for the cloning (port 443).

**Comment by aethaniel** [comment]
documentation will be updated about the ports in use

**Comment by pustekuchen91** [comment]
Hello @aethaniel,

thank you for your response. For the furture it would be the best if not just the system proxy is used. the system proxy (WinHTTP) is not configured in some envoironments for safety reason. instead only the WinInet proxy is configured, which is not used bei CM.
Why not add command line parameter for the proxy configuration, which will be passed by MPLAB X

**Comment by aethaniel** [comment]
I hear you!

I don't know much about system proxy (WinHTTP) not being safe. In fact, my bad, I almost never used any proxy within the last 15 years. Anyway, we will investigate on how to configure it or WinInet one from Java.

Content Manager is used either from within MPLAB X or standalone for users not using MPLAB X. So, I would prefer to have one good solution for both usage, if possible. I will check with my team how we can provide something seamless (I already created a ticket internally for that).

Please be patient.
